version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
    working_directory: /redis_cluster
    steps:
      - checkout
      - run: bundle install

      - run: .circleci/install.sh
      - run: .circleci/start.sh

      - run: rake
